### ISSUE TITLE
Relation manager attach modal breaks the edit modal

### ISSUE THREAD

**Issue by oddvalue** [filamentphp/filament#2792]
### Package

filament/filament

### Package Version

2.13.4

### Laravel Version

9.17.0

### Livewire Version

2.10.5

### PHP Version

8.0.16

### Bug description

The label of the top field on the edit modal is replaced with a choices input when the attach modal is opened.

### Steps to reproduce

This is how it should look:
![image](https://user-images.githubusercontent.com/10127404/174025230-8db421dd-bafe-4ad4-afe4-590128a5d385.png)

When I click on the attach button I get this error in the console:
![image](https://user-images.githubusercontent.com/10127404/174025392-38e18ee5-2abb-4cd5-a587-17ef6a19d8ca.png)

After closing the attach modal the edit modal looks like this:
![image](https://user-images.githubusercontent.com/10127404/174025557-83fc6ffc-7257-414a-a7d1-c29eb07b36d9.png)

And there's a new error in the console:
![image](https://user-images.githubusercontent.com/10127404/174025644-c99ff7a6-418d-46a1-902b-863467fac24c.png)

### Relevant log output

```shell
module.esm.js:4084 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at g.createHiddenContainer (module.esm.js:4084:295)
    at g.parse (module.esm.js:4077:25)
    at g.parse (module.esm.js:4071:46)
    at l.fromHTML (module.esm.js:4276:34)
    at e.loadHTML (module.esm.js:4962:75)
    at module.esm.js:25061:36
    at module.esm.js:2153:9
g.createHiddenContainer @ module.esm.js:4084
g.parse @ module.esm.js:4077
g.parse @ module.esm.js:4071
l.fromHTML @ module.esm.js:4276
e.loadHTML @ module.esm.js:4962
(anonymous) @ module.esm.js:25061
(anonymous) @ module.esm.js:2153
module.esm.js:416 Alpine Expression Error: Cannot read properties of undefined (reading 'toString')

Expression: "state.toString()"

 <button x-data=​"{ state:​ $wire.entangle('mountedTableActionData.highlight')​.defer }​" role=​"switch" aria-checked x-bind:aria-checked=​"state.toString()​" x-on:click=​"state = ! state" x-bind:class=​"{
                    'bg-primary-600':​ state,
                    'bg-gray-200  dark:​bg-white/​10 ':​ ! state,
                }​" id=​"mountedTableActionData.highlight" dusk=​"filament.forms.mountedTableActionData.highlight" type=​"button" class=​"relative inline-flex shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:​outline-none focus:​border-primary-500 focus:​ring-2 focus:​ring-primary-500 disabled:​opacity-70 disabled:​cursor-not-allowed disabled:​pointer-events-none filament-forms-toggle-component border-gray-300 bg-gray-200 dark:​bg-white/​10">​…​</button>​
U @ module.esm.js:416
(anonymous) @ module.esm.js:489
Promise.catch (async)
(anonymous) @ module.esm.js:489
z @ module.esm.js:409
(anonymous) @ module.esm.js:2572
n @ module.esm.js:1571
scheduler @ module.esm.js:52
(anonymous) @ module.esm.js:1702
De @ module.esm.js:1707
(anonymous) @ module.esm.js:1792
N @ module.esm.js:373
(anonymous) @ module.esm.js:348
(anonymous) @ SupportAlpine.js:218
disableEffectScheduling @ module.esm.js:42
(anonymous) @ SupportAlpine.js:217
(anonymous) @ index.js:139
(anonymous) @ index.js:139
(anonymous) @ index.js:127
(anonymous) @ index.js:120
value @ index.js:117
value @ index.js:283
value @ index.js:269
value @ index.js:11
(anonymous) @ index.js:69
Promise.then (async)
(anonymous) @ index.js:64
Promise.then (async)
value @ index.js:62
sendMessage @ index.js:242
value @ index.js:252
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:225
(anonymous) @ node_initializer.js:243
value @ index.js:582
(anonymous) @ node_initializer.js:201
module.esm.js:420 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at eval (eval at <anonymous> (module.esm.js:471:14), <anonymous>:3:38)
    at module.esm.js:489:21
    at z (module.esm.js:409:12)
    at module.esm.js:2572:17
    at n (module.esm.js:1571:16)
    at Object.scheduler (module.esm.js:52:7)
    at module.esm.js:1702:23
    at Set.forEach (<anonymous>)
    at De (module.esm.js:1707:11)
    at Object.set (module.esm.js:1792:9)
eval @ VM17092:3
(anonymous) @ module.esm.js:489
z @ module.esm.js:409
(anonymous) @ module.esm.js:2572
n @ module.esm.js:1571
scheduler @ module.esm.js:52
(anonymous) @ module.esm.js:1702
De @ module.esm.js:1707
(anonymous) @ module.esm.js:1792
N @ module.esm.js:373
(anonymous) @ module.esm.js:348
(anonymous) @ SupportAlpine.js:218
disableEffectScheduling @ module.esm.js:42
(anonymous) @ SupportAlpine.js:217
(anonymous) @ index.js:139
(anonymous) @ index.js:139
(anonymous) @ index.js:127
(anonymous) @ index.js:120
value @ index.js:117
value @ index.js:283
value @ index.js:269
value @ index.js:11
(anonymous) @ index.js:69
module.esm.js:4084 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at g.createHiddenContainer (module.esm.js:4084:295)
    at g.parse (module.esm.js:4077:25)
    at g.parse (module.esm.js:4071:46)
    at l.fromHTML (module.esm.js:4276:34)
    at e.loadHTML (module.esm.js:4962:75)
    at module.esm.js:25061:36
    at module.esm.js:2153:9
g.createHiddenContainer @ module.esm.js:4084
g.parse @ module.esm.js:4077
g.parse @ module.esm.js:4071
l.fromHTML @ module.esm.js:4276
e.loadHTML @ module.esm.js:4962
(anonymous) @ module.esm.js:25061
(anonymous) @ module.esm.js:2153
```

**Comment by zepfietje** [comment]
Can you provide us a reproduction repository URL and then we'll look at your issue? That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by oddvalue** [comment]
The page this issue was happening on no longer exists in our project and I've not been able to replicated it so will close for now.
