### ISSUE TITLE
Submitting create form on relation manager for pivot model throws exception

### ISSUE THREAD

**Issue by oddvalue** [filamentphp/filament#2888]
### Package

filament/filament

### Package Version

2.13.4

### Laravel Version

9.17.0

### Livewire Version

2.10.5

### PHP Version

8.0.16

### Bug description

When using a relation to a pivot model as the target for a relation manager you get the following exception upon submitting the form:

> Filament\Resources\RelationManagers\RelationManager::getTableRecordKey(): Return value must be of type string, null returned

### Steps to reproduce

I've put together a demo app showing the error: https://github.com/oddvalue/filament-relation-manager-bug
Just follow the instructions in the readme

### Relevant log output

```shell
[2022-06-22 11:15:19] local.ERROR: Filament\Resources\RelationManagers\RelationManager::getTableRecordKey(): Return value must be of type string, null returned {"view":{"view":"/var/www/html/vendor/filament/tables/resources/views/components/actions/action.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Filament\\Resources\\RelationManagers\\RelationManager::getTableRecordKey(): Return value must be of type string, null returned at /var/www/html/vendor/filament/tables/src/Concerns/HasRecords.php:88)
[stacktrace]
#0 /var/www/html/vendor/filament/tables/src/../resources/views/components/actions/action.blade.php(7): Filament\\Resources\\RelationManagers\\RelationManager->getTableRecordKey()
#1 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#2 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#3 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\\View\\View->render()
#8 /var/www/html/vendor/filament/tables/src/../resources/views/actions/button-action.blade.php(8): Illuminate\\View\\Factory->renderComponent()
#9 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#10 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#11 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#15 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(43): Illuminate\\View\\View->render()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#17 /var/www/html/vendor/filament/tables/src/../resources/views/components/actions/index.blade.php(7): e()
#18 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#19 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#20 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\\View\\View->render()
#25 /var/www/html/vendor/filament/tables/src/../resources/views/components/header/index.blade.php(23): Illuminate\\View\\Factory->renderComponent()
#26 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#27 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#28 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\\View\\View->render()
#33 /var/www/html/vendor/filament/tables/src/../resources/views/index.blade.php(236): Illuminate\\View\\Factory->renderComponent()
#34 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#35 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#36 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#40 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(43): Illuminate\\View\\View->render()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#42 /var/www/html/vendor/filament/filament/src/../resources/views/resources/relation-manager.blade.php(2): e()
#43 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#44 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#45 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#49 /var/www/html/vendor/livewire/livewire/src/Component.php(235): Illuminate\\View\\View->render()
#50 /var/www/html/vendor/livewire/livewire/src/HydrationMiddleware/RenderView.php(14): Livewire\\Component->output()
#51 /var/www/html/vendor/livewire/livewire/src/LifecycleManager.php(154): Livewire\\HydrationMiddleware\\RenderView::dehydrate()
#52 /var/www/html/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(15): Livewire\\LifecycleManager->dehydrate()
#53 /var/www/html/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#79 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#93 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#95 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#96 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#97 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#98 {main}

[previous exception] [object] (TypeError(code: 0): Filament\\Resources\\RelationManagers\\RelationManager::getTableRecordKey(): Return value must be of type string, null returned at /var/www/html/vendor/filament/tables/src/Concerns/HasRecords.php:88)
[stacktrace]
#0 /var/www/html/storage/framework/views/57fcdaa68a71f1d4008c8680719388bcff24c646.php(30): Filament\\Resources\\RelationManagers\\RelationManager->getTableRecordKey()
#1 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#2 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#3 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\\View\\View->render()
#8 /var/www/html/storage/framework/views/a01cdd75868e8a59d1e64101eac74646e4fabf8b.php(12): Illuminate\\View\\Factory->renderComponent()
#9 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#10 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#11 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#15 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(43): Illuminate\\View\\View->render()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#17 /var/www/html/storage/framework/views/0f36c21da69bdb0be0f610597b657df9e2b9f2b3.php(22): e()
#18 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#19 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#20 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\\View\\View->render()
#25 /var/www/html/storage/framework/views/7f7c4d1d2dc7d074fa5c6510722ed9587da31444.php(79): Illuminate\\View\\Factory->renderComponent()
#26 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#27 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#28 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\\View\\View->render()
#33 /var/www/html/storage/framework/views/8996070eebe7f42a80e648b779c7f4a565cc7cee.php(258): Illuminate\\View\\Factory->renderComponent()
#34 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#35 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#36 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#40 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(43): Illuminate\\View\\View->render()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#42 /var/www/html/storage/framework/views/95f3aa5035f44e79bc871e2bc0880ce95f0fdb24.php(2): e()
#43 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#44 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\PostResource\\RelationManagers\\TagsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#45 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#49 /var/www/html/vendor/livewire/livewire/src/Component.php(235): Illuminate\\View\\View->render()
#50 /var/www/html/vendor/livewire/livewire/src/HydrationMiddleware/RenderView.php(14): Livewire\\Component->output()
#51 /var/www/html/vendor/livewire/livewire/src/LifecycleManager.php(154): Livewire\\HydrationMiddleware\\RenderView::dehydrate()
#52 /var/www/html/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(15): Livewire\\LifecycleManager->dehydrate()
#53 /var/www/html/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#79 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#93 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#95 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#96 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#97 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#98 {main}
"} 

```

**Comment by danharrin** [comment]
Is the goal to be able to CRUD & attach tags? it feels wrong that you're targeting the pivot model instead of the tags

**Comment by oddvalue** [comment]
In the app I'm actually working on I'm attaching roles to users but the pivot model also has relations to other models that affect how the relationship to the role behaves in the app.

**Comment by oddvalue** [comment]
The idea is that you select the role you want to link to and the other model in the relation manager modal.

**Comment by oddvalue** [comment]
My bad, it's a Laravel thing, not a Filament thing. The pivot model needs to have the `$increments` property set to true in order to return the id when it's created.
