### ISSUE TITLE
SpatieTagsInput do not escape single quotes

### ISSUE THREAD

**Issue by markkimsal** [filamentphp/filament#4241]
### Package

filament/spatie-laravel-tags-plugin

### Package Version

v2.15.10

### Laravel Version

v9.23.0

### Livewire Version

v2.10.6

### PHP Version

8.0.16

### Problem description

Adding a spatie tag with a single quote, like "Brian O'Hara" will result in javascript errors when loading a page that wants to show that tag value as a type-ahead value.

### Expected behavior

spatie tags escapes the result of component->state($tags->pluck('name')->toArray())

### Steps to reproduce

crate a form schema like
```
                    Section::make('Tags')
                        ->schema([

                            SpatieTagsInput::make('subject')
                                ->name("Subject")
                                ->type('subject'),
                        ]),
```

Add a tag like "Brian O'Hara"

Reload the form.

### Reproduction repository

https://github.com/markkimsal/spatie-tags-demo

### Relevant log output

```shell
module.esm.js:416 Alpine Expression Error: missing ) after argument list

Expression: "! state.includes('brian o'hara')"

 <template x-if=​"! state.includes('brian o'hara')​" x-bind:key=​"'brian o'hara'">​…​</template>​
U @ module.esm.js:416
(anonymous) @ module.esm.js:473
(anonymous) @ module.esm.js:477
(anonymous) @ module.esm.js:482
$ @ module.esm.js:451
W @ module.esm.js:438
(anonymous) @ module.esm.js:2880
n @ module.esm.js:561
(anonymous) @ module.esm.js:566
It @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
216 @ app.js:75
i @ bootstrap:19
(anonymous) @ startup:4
i.O @ chunk loaded:23
(anonymous) @ startup:6
(anonymous) @ app.js?id=8561bb94452ab7fd77efab3a3b09a87a:73
module.esm.js:471 Uncaught SyntaxError: missing ) after argument list
    at new AsyncFunction (<anonymous>)
    at module.esm.js:471:14
    at module.esm.js:477:14
    at module.esm.js:482:14
    at $ (module.esm.js:451:19)
    at W (module.esm.js:438:10)
    at Function.<anonymous> (module.esm.js:2880:19)
    at n (module.esm.js:561:7)
    at module.esm.js:566:5
    at It (module.esm.js:778:3)
```
```

**Comment by markkimsal** [comment]
```
  $component->state($tags->pluck('name')->map(fn($name) => htmlspecialchars($name, ENT_QUOTES))->toArray())
```

This produces &#039;hara vaules in the tag badges, but still the bad JS in the <x-template tags

![image](https://user-images.githubusercontent.com/54099/192643990-3e361f93-e1ef-4d4a-bef3-c47b6cd705cf.png)

**Comment by markkimsal** [comment]
this is what fixed it for me.
in vendor/filamentphp/forms 

add @js() around the $suggestion in
 resources/views/components/tags-input.blade.php
```
                      <datalist id="{{ $getId() }}-suggestions">
                          @foreach ($getSuggestions() as $suggestion)
                              <template x-if="! state.includes(@js('{{ $suggestion }}'))" x-bind:key="'{{ $suggestion }}'">
                                  <option value="{{ $suggestion }}" />
                              </template>
                          @endforeach
                      </datalist>

```

**Comment by markkimsal** [comment]
this is what the repo has, simple edit user form, one tag, enter value of "o'hara", reload, see js errors

![image](https://user-images.githubusercontent.com/54099/192650781-51b70dee-cd3d-4e63-8150-ca6bd2c67c6f.png)
